### ISSUE TITLE
does this idp support multi sps?

### ISSUE THREAD

**Issue by jhyvictory** [mcguinness/saml-idp#21]
BTW: when i test this idp with saml-sp, i met this error ---- PEM_read_bio_PUBKEY failed, what's the problem?

**Comment by jhyvictory** [comment]
- sp command: node ./bin/server.js --iss urn:example:idp --idpSsoUrl http://localhost:7000 --idpCert="config/idp-public-cert.pem" --spCert="config/sp-cert.pem" --spKey="config/sp-key.pem"

- idp command: node app.js --acs http://localhost:7070 --aud http://localhost:7070 --encCert="test/sp-cert.pem" --encKey="test/sp-pub.key"

- i use your two sample projects like this and the certs and keys i used were the ones in your directory. i copied the sp's cert into the idp's test directory and generated sp-pub.key, also copied idp's idp-public-cert.pem into sp's config directory. did i really make some error?

**Comment by mcguinness** [comment]
I recently refactored saml-sp and its doing something weird when parsing the idp cert and trying to strip off the PEM wrapper.  Was testing using ```idpMetaUrl```.  Will try to patch later.

Thanks for filing the issue.

**Comment by mcguinness** [comment]
Ok, pushed a fix to saml-sp

`node app.js --acs http://localhost:7070 --aud urn:example:sp --encCert ../saml-sp/config/sp-cert.pem --encKey ../saml-sp/config/sp-key.pem`

` node ./bin/server.js --iss urn:example:idp --idpSsoUrl http://localhost:7000 --idpCert ../saml-idp/idp-public-cert.pem `

**Comment by jhyvictory** [comment]
okay! the problem is solved. and how can i let this idp support many sps, afterall in the running command "node app.js --acs http://localhost:7070 --aud urn:example:sp --encCert ../saml-sp/config/sp-cert.pem --encKey ../saml-sp/config/sp-key.pem" there is only one sp.

**Comment by mcguinness** [comment]
This project isn't intended to be a full production IdP so its a bit out of scope.  Running the server on multiple ports with different configs (e.g docker) is the intended scenario for testing multiple SPs.

This project is really just a wrapper around a SAMLP library.  If you have a specific use case it might just be easier to generate your own responses (see https://github.com/mcguinness/saml-idp/blob/master/app.js#L443)
