### ISSUE TITLE
NPM install fails with node v9

### ISSUE THREAD

**Issue by john-aws** [mcguinness/saml-idp#26]
Hi,

I'm using node v9.9.0 and npm v5.6.0. Running npm install fails with numerous issues:

- npm WARN tar ENOENT: no such file or directory, open 'saml-idp/node_modules/.staging/node-forge-1f943e2d/dist/forge.min.js'
- (repeat last ENOENT for dozens of other packages)
- npm ERR! code EINTEGRITY
- npm ERR! sha1-Yq9xD8gtQpVtjmkYvRus+FFjyzc= integrity checksum failed when using sha1: wanted sha1-Yq9xD8gtQpVtjmkYvRus+FFjyzc= but got sha1-7SlRb/DIDZxfF9ukd4CGgy70ink=. (98083 bytes)

**Comment by john-aws** [comment]
Seems to work if I switch to node v8.10.0 (with npm v5.6.0).

**Comment by JohnnyFun** [comment]
fwiw, works on v10.15.1
