### ISSUE TITLE
Why is --acsUrl a required parameter?

### ISSUE THREAD

**Issue by john-aws** [mcguinness/saml-idp#29]
For an SP-initiated SSO, the SP can specify the required ACS endpoint in the AuthnRequest so I'm wondering why saml-idp needs to know this URL in advance (and requires the --acsUrl parameter to be provided).

I'm asking this in the context of using a single saml-idp instance for multiple SPs, each with their own unique ACS URL.

Thanks.

**Comment by mcguinness** [comment]
The app supports using the ACS value from the SAMLRequest by default (`disableRequestAcsUrl` can be used to turn-off).  The param is required for IdP-init scenarios.  If your use case is just SP-init only then you can just pass a random value.

**Comment by john-aws** [comment]
OK, and that's what I'm doing. Thanks for the response.

**Comment by benjaminlaib** [comment]
@mcguinness wouldn't it make more sense to just disable IdP initiated SSO if `acsUrl` is not passed?

**Comment by mcguinness** [comment]
sure, just code that needs to be written!

**Comment by benjaminlaib** [comment]
> sure, just code that needs to be written!

I will try finding some time for that during the next days. I was thinking about making a PR to implement a feature for sending negative responses (e.g. wrong password) anyways.

**Comment by mcguinness** [comment]
that would be awesome!  its been fun to see folks add their use cases.  this started off a quick test tool as no one likes to hand craft saml messages.

**Comment by benjaminlaib** [comment]
We will actually probably use this as a testing tool in the company I work for, and if we do, I will actually be paid for making pull requests. :D
