### ISSUE TITLE
An example would be awesome

### ISSUE THREAD

**Issue by nlfiedler** [mcguinness/saml-idp#30]
I'm submitting an authn request and the only hidden input values of any form the response is the `_authnRequest`. I was expecting to see `SAMLResponse` and `RelayState`, as described in the Web Browser SSO Profile example on the Wikipedia page. I think a short example of using this test service would help a lot.

**Comment by mcguinness** [comment]
Checkout https://github.com/mcguinness/saml-sp for an sample implementation of a SAML service provider.  You can see the request message with your browser debug tools.  The service provider supports both a Redirect and Form POST binding.

The simplest way to test is with Redirect binding using `http://localhost:7000/idp?SAMLRequest=request`. 

If using POST binding your HTML form should look something like

```
  <form method="post" action="http://localhost:7000/idp" ...>
    <input type="hidden" name="SAMLRequest" value="request" />
    <input type="hidden" name="RelayState" value="token" />
    ...
    <input type="submit" value="Submit" />
  </form>
```

**Comment by nlfiedler** [comment]
Okay, I'll take a look at that. I failed to mention that I am writing the "User Agent" piece, so I need to make a request against both the IdP and the SP. Hence I'm trying to work out how to implement step 3 of the Web Browser SSO Profile ("Request the SSO Service at the IdP") and get the expected response described in step 4. Maybe I have to use POST instead of GET?
