### ISSUE TITLE
Logout Support

### ISSUE THREAD

**Issue by yevgenb** [mcguinness/saml-idp#35]
Does this IDP supports SAML logout?

**Comment by sleyzerzon** [comment]
I too have exactly the same question and looking for that feature

**Comment by mcguinness** [comment]
It currently doesn't.  Do you just need support to initiate sign-out from the SP and return LogoutResponse from the IDP?

**Comment by sleyzerzon** [comment]
My use case is actually IdP initiated so I would want to receive a LogoutRequest from the IdP which initially sent a SAML response to my SP.  Possibly an SP-initiated SLO would be nice to have too, but it's currently out of scope AFAIK.

**Comment by mcguinness** [comment]
Just added a basic implementation of both IdP and SP init SLO.  Check it out and let me know.
