### ISSUE TITLE
metadata reports incorrect logout URL

### ISSUE THREAD

**Issue by nlfiedler** [mcguinness/saml-idp#36]
Looking at the output from `/metadata` indicates that the logout URL is `/logout`, but it is in fact hard-coded to `/signout` in `app.js`. This is in a freshly cloned and built instance, no customization whatsoever. Where is the metadata coming from, by the way? I can't even see how to fix it.

**Comment by mcguinness** [comment]
Just updated the project with support for SAML SLO and the metadata should be correct.

**Comment by nlfiedler** [comment]
Terrific, thank you.
