### ISSUE TITLE
Replace Bower

### ISSUE THREAD

**Issue by valerauko** [mcguinness/saml-idp#42]
Bower's been deprecated apparently. Would you mind if I posted a PR replacing it with Yarn?

**Comment by JohnnyFun** [comment]
Maybe I'm missing something simple, but it appears version 1.1.0 still contains bower dependency? `bower.json` is still present and when I fire up the server, there are a bunch of 404s for jquery, boostrap, etc coming from endpoint like `bower_components`.

Thanks very much for building this, btw. Despite the 404s, I'm still able to do SSO testing locally--just a few missing thingamabobs.

**Comment by matuszeman** [comment]
> Maybe I'm missing something simple, but it appears version 1.1.0 still contains bower dependency? `bower.json` is still present and when I fire up the server, there are a bunch of 404s for jquery, boostrap, etc coming from endpoint like `bower_components`.
> 
> Thanks very much for building this, btw. Despite the 404s, I'm still able to do SSO testing locally--just a few missing thingamabobs.

It looks like it has been forgotten in dependupdate branch.
