### ISSUE TITLE
Default value for nameIdFormat not working due to whitespaces

### ISSUE THREAD

**Issue by chumbalum** [mcguinness/saml-idp#48]
Hi,

currently default values for nameIdFormat are not reflected. For example with the following config:

```
userDefaults = {
 nameIdFormat: "urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified"
}
```

I made some research and it seems like this issue is caused by the whitespaces in the select options in the markup. After I removed them, the default values were correctly applied.

https://github.com/mcguinness/saml-idp/blob/6ab88ae417ae4c23ceb0c9c9b687c21d778ae5cc/views/user.hbs#L84

**Comment by mcguinness** [comment]
Can you submit a PR to resolve this?

**Comment by chumbalum** [comment]
Hi @mcguinness 

I created a pull request for this issue

**Comment by chumbalum** [comment]
Ok, I guess this can be closed now. Thanks
