### ISSUE TITLE
SP options via metadata.xml 

### ISSUE THREAD

**Issue by nao3301** [mcguinness/saml-idp#49]
it would be great, if the sp options could be read from xml,

Nice project by the way!

**Comment by shaleh** [comment]
Add a xml parser, grab the needed fields. Could even take the XML as a URL and retrieve it when needed. Should be pretty straight forward.

**Comment by mcguinness** [comment]
Feel free to open a PR to add your use case,  its trivial to parse config with https://yargs.js.org/docs/#api-configkey-description-parsefn
