### ISSUE TITLE
Not really clear how to use

### ISSUE THREAD

**Issue by newmanw** [mcguinness/saml-idp#59]
I have a saml SP and would like to test the authentication flow.  Is that possible with this application?  If so the documentation isn't really clear on how to setup test users and credentials.

**Comment by mcguinness** [comment]
This project doesn't really have users or "authentication".  It mints a SAMLResponse with whatever SAML Subject or SAML AttributeStatement you want.  The IdP is just a WebForm to construct details for the assertion.  You configure the SAML Trust using CLI args and/or the Settings page.

**Comment by newmanw** [comment]
Thanks for the response, sorry for the confusion.  I am looking to test a SP initiated login.

**Comment by mcguinness** [comment]
You can test SP initiated login.  Just set the CLI arguments for your SP and redirect to http://localhost:7000/saml/sso the default port.
