### ISSUE TITLE
Getting 404 for all `bower_components`

### ISSUE THREAD

**Issue by gcoonrod** [mcguinness/saml-idp#61]
I'm using `runServer` to create a saml-idp server in a node project. When I try the idp login I see a lot of 404s for jquery, underscore, etc that are in the `bower_components` folder.

**Comment by sklarsa** [comment]
Experiencing the same issue here.  Lots of static files not loading after I've `npm install`ed the package and running the server.

**Comment by karlmcguinness-okta** [comment]
just did a fresh `git clone && npm install` in a new directory and not able to reproduce

**Comment by mcguinness** [comment]
Just did a fresh `git clone && npm update` in a new directory and not able to reproduce

**Comment by mcguinness** [comment]
`bower_components` no longer used
