### ISSUE TITLE
recommend samltest.id as  demo

### ISSUE THREAD

**Issue by Jamlee** [mcguinness/saml-idp#66]
start the idp server:

```bash
npm install -g saml-idp
saml-idp --audience https://samltest.id/saml/sp --acsUrl  https://samltest.id/Shibboleth.sso/SAML2/POST 
```
upload metadata
![image](https://user-images.githubusercontent.com/5196641/113804288-d89a2e80-9790-11eb-998a-cdc604ead4e2.png)

go to test, https://samltest.id/
![image](https://user-images.githubusercontent.com/5196641/113804338-ecde2b80-9790-11eb-91ca-3c6f85ed4f78.png)
![image](https://user-images.githubusercontent.com/5196641/113804362-f8315700-9790-11eb-9176-ea631d11e91f.png)

get the result
![image](https://user-images.githubusercontent.com/5196641/113804243-c0c2aa80-9790-11eb-9a21-1da5f760a283.png)

**Comment by mcguinness** [comment]
This project is designed to bring your own SP for testing not have a default SP.
