### ISSUE TITLE
Returning `httpServer` object from `runServer`

### ISSUE THREAD

**Issue by JakubPetriska** [mcguinness/saml-idp#71]
Hello, first of all thanks for this amazing library. I'm using it in automated tests to test my SSO service provider implementation and it helped me a lot.

I have one issue though. As I'm starting the server for each automated test I'd like to kill the server at the end of each test. This is currently not possible as the `runServer` function does not return the `httpServer` object.

I already have this implemented on my machine and can submit PR. Would it be possible to add this to the library?

**Comment by Devlin556** [comment]
@JakubPetriska great idea, I just wanted to write about it :-D Thank you! I'm waiting for your implementation

**Comment by JakubPetriska** [comment]
Nice, that's awesome. Here it is https://github.com/mcguinness/saml-idp/pull/72
