### ISSUE TITLE
IDP Server cannot be stopped gracefully in jest integration tests

### ISSUE THREAD

**Issue by anijain-Amazon** [mcguinness/saml-idp#80]
I am using runServer to start a IDP Server in the beforeAll setup of a JEST Integration test. 

```
runServer({
  acsUrl: 'http://localhost:5602/_opendistro/_security/saml/acs',
  audience: 'https://localhost:9200',
});
```

Since, this method returns void there is no handle available to stop the server, this keeps the JEST ITs to remain hung with the message 

`This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with --detectOpenHandles to troubleshoot this issue.`

A simple workaround is to use the option `--force-kill` to stop the Jest server. Is there a graceful manner of shutting down the IDP Server ?

**Comment by anijain-Amazon** [comment]
Looks like a recent [commit](https://github.com/mcguinness/saml-idp/blame/master/app.js#L820) has introduced returning the http server. The recent version `1.2.1` available via yarn doesn't have this change. 

Waiting for the new release into yarn repository.

**Comment by mbroadhead-nr** [comment]
@expani when do you think the new release will be?  It has been a couple of years
