### ISSUE TITLE
Loosen `parseSamlRequest` and `showUser`

### ISSUE THREAD

**Issue by jazelly** [mcguinness/saml-idp#84]
First of all, great repo. I've been using this for a few months, and it saved me a lot of time on testing SSO based on SAML.

`parseSamlRequest` does not do any work for IDP-initiated flow, as there is no `SAMLRequest`, so kind of not making sense to have that as a handler for IDP-initiated endpoint, which is `GET /, /idp, /saml/sso`.

**Comment by caolainia** [comment]
I guess this was intentional, as some SP request IDP by post, some by get. So probably this is a won't do, but might be great to loose couple `parseSamlRequest` and `showUser`
