### ISSUE TITLE
CORS errors?

### ISSUE THREAD

**Issue by bazfer** [mcguinness/saml-idp#89]
Hello, just fired up a small app using your lib 1.2.1, server spins up but when I navigate to localhost://7000, I get a 403. Suspecting CORS, but I imagine that should be handled already? Any pointers are welcome.

```
Access to localhost was deniedYou don't have authorization to view this page.
HTTP ERROR 403
```

**Comment by mcguinness** [comment]
What are you trying to do via CORS? SAML is browser based flow and uses HTML

**Comment by jdf-id-au** [comment]
Thank you for this extremely helpful project.

I'm also getting 403 trying to reach `http://localhost:7000/metadata` using java-saml's [`parseRemoteXML`](https://github.com/SAML-Toolkits/java-saml/blob/5a584102848552843337106facaf772e0d9d8655/core/src/main/java/com/onelogin/saml2/settings/IdPMetadataParser.java#L285) which in turn uses java's URL `.openStream`. Works fine from local browser.

**Comment by mcguinness** [comment]
This helps. It’s metadata fetch that needs CORS.

**Comment by bazfer** [comment]
> What are you trying to do via CORS? SAML is browser based flow and uses HTML

I'm not trying to do anything with CORS -- I just want to run the app but get that error as soon as I launch it.

**Comment by bazfer** [comment]
Actually, this 403 error I'm seeing only happens in Chrome, Firefox works fine. Closing.
