### ISSUE TITLE
Next is not a function error

### ISSUE THREAD

**Issue by shinyford** [mcguinness/saml-idp#9]
Hi - no matter how I configure saml-idp, when I click on the sign-in button I get the following error:

```
/Users/nicford/Source/Ascential/shared/saml-idp/node_modules/samlp/lib/samlp.js:164
      if (err) return next(err);
                      ^

TypeError: next is not a function
    at /Users/nicford/Source/Ascential/shared/saml-idp/node_modules/samlp/lib/samlp.js:164:23
    at /Users/nicford/Source/Ascential/shared/saml-idp/node_modules/samlp/lib/utils.js:86:27
    at InflateRaw.onError (zlib.js:198:5)
    at emitOne (events.js:96:13)
    at InflateRaw.emit (events.js:191:7)
    at Zlib._handle.onerror (zlib.js:358:10)
```

It's probably just a configuration error at my end (relatively new to SAML) but if you have any insights I'd appreciate them.

Many thanks

Nic Ford

**Comment by mcguinness** [comment]
I just pushed a change that hopefully displays a better error message.  I think your SAML SP is compressing the AuthnRequest message and the node app is not decoding it right

**Comment by shinyford** [comment]
Fantastic - many thanks. I'll pull and check.

**Comment by shinyford** [comment]
Hm. That's now giving me the following error all the time, before I even get to the display of the sign-in button:
```
SAML AuthnRequest Parse Error: invalid distance too far back
Error: invalid distance too far back
    at Zlib._handle.onerror (zlib.js:355:17)
```
The AuthnRequest XML I'm generating works fine against Okta - but happy to hear if there are any gotchas. Sample XML below:
```
<samlp:AuthnRequest
        xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
        xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
        ID="1a3c3c54-7aa2-460d-9f14-cda5e7fe9fbd"
        Version="2.0"
        IssueInstant="2017-03-13T17:51:14.760593Z"
        AssertionConsumerServiceIndex="0">
        <saml:Issuer>http://www.okta.com/exk1mb9ytvvUrhDdf1t7</saml:Issuer>
        <samlp:NameIDPolicy
          AllowCreate="true"
          Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient"/>
</samlp:AuthnRequest>
```

**Comment by mcguinness** [comment]
I can repro the issue using https://www.samltool.com/encode.php.  What is your SAML toolkit for your SP?

**Comment by shinyford** [comment]
At this stage, nothing - it's just a spike, so the XML is pretty-much hard coded with only a few attributes and text values varying.

However, I think that tells me what's missing: we're not deflating the xml, which Okta is fine with. But of course, that's not to the spec. Let me try adding deflation to the mix and see if that fixes it.

**Comment by mcguinness** [comment]
The code just calls `zlib.inflateRaw(input, function(err, buffer)` which is being rejected with `incorrect header check`.  Need to dig in more as well.  I know Okta does a bunch of guessing on inflate as so many SPs deflate incorrectly.  My JS is more strict here.

**Comment by shinyford** [comment]
Yes, that was I guess the problem all along - the fact that our xml wasn't deflated before Base64 encoding. Thanks for taking the time to reply.
