### ISSUE TITLE
Can I use for testing with Keycloak? 

### ISSUE THREAD

**Issue by tkrisztian95** [mcguinness/saml-idp#91]
Hello!

I'm interested in using the project for mock testing logins with Keycloak where IDP is used.  Do you know if this should work with configuring in Keycloak to connect to the server started from this lib?

Thanks a lot!

**Comment by mcguinness** [comment]
Yes, you should be able to configure a SAML SP trust relationship with Keycloak such as https://access.redhat.com/documentation/en-us/red_hat_build_of_keycloak/22.0/html/server_administration_guide/identity_broker#saml_v2_0_identity_providers
